name: Slack CLI Command Runner
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Slack CLI command to run'
        type: string
        default: ""
        required: true
      verbose:
        description: 'Verbose flag'
        type: boolean
        default: false
        required: false
      cli_version:
        description: 'CLI version'
        type: string
        default: "latest"
        required: false
      app_id: 
        description: "App ID"
        type: string
        default: ""
        required: false

jobs:
  run-slack-cli:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Slack CLI Command
        uses: slackapi/slack-cli-action@v1
        with:
          command: ${{ github.event.inputs.command }}
          verbose: ${{ github.event.inputs.verbose || github.run_attempt > 1 }}
          cli_version: ${{ github.event.inputs.cli_version }}
          app_id: ${{ github.event.inputs.app_id }}
        secrets: inherit
        #hey