name: Slack CLI Command Runner
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Slack CLI command to run'
        required: true
      verbose:
        description: 'Verbose flag'
        type: boolean
        default: false
      cli_version:
        description: 'CLI version'
        required: false
        default: "latest"
      app_id: 
        description: "App ID"
        required: false

jobs:
  run-slack-cli:
    uses: ewanek1/slack-deploy-playground/.github/workflows/cli-runner.yml@main
    with:
      command: ${{ github.event.inputs.command }}
      verbose: ${{ github.event.inputs.verbose }}
      cli_version: ${{ github.event.inputs.cli_version }}
      app_id: ${{ github.event.inputs.app_id }}